
lint.select = [
  "E",
  "F",
  "B",
  "W",
  "C90",
  "I",
  "N",
  "D",
  "UP",
  "S",
  "ASYNC",
  "BLE",
  "FBT",
  "A",
  "COM",
  "C4",
  "DTZ",
  "EM",
  "FA",
  "ISC",
  "ICN",
  "G",
  "T20",
  "PYI",
  "RET",
  "RSE",
  "SLF",
  "SLOT",
  "SIM",
  "TID",
  "TCH",
  "INT",
  "ARG",
  "PTH",
  "TD",
  "FIX",
  "ERA",
  "PD",
  "PL",
  "FLY",
  "RUF",
]
lint.ignore = [
  "D207",
  "D208",
  "D211",
  "D213",
  "D100",
  "EM102",
  "EM101",
  "COM812",
  "ISC001",
]
target-version = "py310"
line-length = 88
lint.fixable = ["ALL"]
[lint.per-file-ignores]
"**/{tests}/*" = ["S101", "D103"]
